"""Add OPeration

Revision ID: 8628a10f4f4a
Revises: ac51dd375cc4
Create Date: 2023-06-25 14:59:27.039764

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8628a10f4f4a"
down_revision = "ac51dd375cc4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.String(), nullable=True),
        sa.Column("figi", sa.String(), nullable=True),
        sa.Column("instrument_type", sa.String(), nullable=True),
        sa.Column("date", sa.TIMESTAMP(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operation")
    # ### end Alembic commands ###
